# Generated by Django 4.2.7 on 2023-11-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_alter_review_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetail',
            name='isbn',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bookdetail',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bookdetail',
            name='pages',
            field=models.IntegerField(null=True),
        ),
    ]
